#!/bin/bash

set -x

function	db_configure()
{
	psql -U postgres -c "CREATE USER ${USER_NAME} WITH PASSWORD '"${USER_PASS}"' ;"
	psql -U postgres -c "CREATE DATABASE ${DB_NAME} OWNER ${USER_NAME};"
	psql -U postgres -c "grant ALL ON DATABASE ${DB_NAME} TO ${USER_NAME};"
}

sudo rc-service -v postgresql start
sudo rc-service -v postgresql setup

db_configure

PATH="${HOME}/.local/bin:${PATH}"

# msfconsole -x "db_connect ${USER_NAME}:${USER_PASS}@127.0.0.1:5432/${DB_NAME}"
# msfconsole -x "db_status"

if [ ${#} != "0" ]; then
	exec ${@}
else
	bash
fi
