version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

################################################################################

services:
  ##############################################################################
  # MAIN
  android:
    container_name: android
    build:
      context: "./android"
      target: "packed"
      args:
        - USER_NAME=${USER_NAME}
        - USER_PASS=${USER_PASS}
        - USER_SHELL=${SHELL}
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      main_net:
        ipv4_address: "13.37.42.10"
    volumes:
      - shared_dir:/Shared
      - ruby:/usr/lib/ruby
    # healthcheck:
    #   test: [ "CMD", "pgwrep", "mysqld" ]
    #   << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # POSTGRESQL
  postgresql:
    container_name: postgresql
    build:
      context: "./postgresql"
      target: "packed"
      args:
        - USER_NAME=${USER_NAME}
        - USER_PASS=${USER_PASS}
        - PGDATA=/var/lib/postgresql/data
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS}
      - DB_NAME=${DB_NAME}
      - PGDATA=/var/lib/postgresql/data
    networks:
      main_net:
        ipv4_address: "13.37.42.11"
    volumes:
      - postgresql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pgrep", "postgresql" ]
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK
  main_net:
    name: main_net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: main_net
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################

volumes:
  ##############################################################################
  # Shared folder
  shared_dir:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared
  #
  ##############################################################################
  ##############################################################################
  # Shared folder
  ruby:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared/ruby
  #
  ##############################################################################
  ##############################################################################
  # postgresql data
  postgresql:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared/db
  #
  ##############################################################################
