version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

################################################################################

services:
  ##############################################################################
  # MAIN
  android:
    container_name: android
    build:
      context: "./android"
      target: "packed"
      args:
        - USER_NAME=${USER_NAME}
        - USER_PASS=${USER_PASS:-pass}
        - USER_SHELL=${SHELL}
    environment:
      - USER_NAME=${USER_NAME}
      - USER_PASS=${USER_PASS:-pass}
      - LHOST=${LHOST:-localhost}
      - LPORT=${LPORT:-4445}
      - APK_TARGET=${APK_TARGET:-}
    networks:
      main_net:
        ipv4_address: "13.37.43.10"
    volumes:
      - shared_dir:/Shared
      - ruby:/usr/lib/ruby
    # healthcheck:
    #   test: [ "CMD", "pgwrep", "mysqld" ]
    #   << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK
  main_net:
    name: main_net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: main_net
    ipam:
      driver: default
      config:
        - subnet: 13.37.43.0/27
          ip_range: 13.37.43.0/27
          gateway: 13.37.43.1
  #
  ##############################################################################

volumes:
  ##############################################################################
  # Shared folder
  shared_dir:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared
  #
  ##############################################################################
  ##############################################################################
  # Ruby with gems
  ruby:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared/ruby
  #
  ##############################################################################
