#!/bin/bash

set -x

function	msf_build()
{
	mkdir -p /home/${USER_NAME}/.msf4
	mkdir -p /home/${USER_NAME}/.bundle

	cd /opt/metasploit-framework && \
		bundle install
}

function	msf_link()
{
	mkdir -p ${HOME}/.local/bin/
	cp -r /opt/metasploit-framework/* ${HOME}/.local/bin/
}

msf_build
msf_link

PATH="${HOME}/.local/bin:${PATH}"

if [ ${#} != "0" ]; then
	exec ${@}
else
	bash
fi
